//! Provider-agnostic abstractions for AI assistant sessions.
//!
//! This module defines the shared types and traits that all provider
//! backends (Claude Code, OpenCode, future providers) must implement.
//! Consumer code (CLI actions, session detection, activity tracking)
//! uses these abstractions exclusively, so adding a new provider
//! requires only implementing `SessionProvider` — no other code changes.

use anyhow::{bail, Result};
use chrono::{DateTime, Utc};
use serde::Serialize;
use std::ops::Add;

use crate::transcript::TranscriptEntry;

/// AI assistant provider identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Provider {
    ClaudeCode,
    OpenCode,
    Pi,
}

impl Provider {
    pub fn as_str(&self) -> &'static str {
        match self {
            Provider::ClaudeCode => "claudecode",
            Provider::OpenCode => "opencode",
            Provider::Pi => "pi",
        }
    }
}

impl std::fmt::Display for Provider {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Detect the provider for a session ID based on its format.
///
/// Recognised formats:
/// - `ses_*` prefix → OpenCode
/// - UUIDv4 (version digit `4`) → Claude Code
/// - UUIDv7 (version digit `7`) → Pi
///
/// Anything else (malformed strings, unknown UUID versions) returns an
/// error.  Loud failure here is intentional: unrecognised IDs are almost
/// always user error or a sign that a new provider exists which the
/// codebase has not yet been taught about.
pub fn detect_provider(session_id: &str) -> Result<Provider> {
    if session_id.starts_with("ses_") {
        return Ok(Provider::OpenCode);
    }
    if !looks_like_hyphenated_uuid(session_id) {
        bail!(
            "Unrecognised session ID format: {:?} (expected ses_* for OpenCode, \
             UUIDv4 for Claude Code, or UUIDv7 for pi)",
            session_id
        );
    }
    // Version nibble is the 15th character (index 14) of a hyphenated UUID.
    match session_id.as_bytes()[14] {
        b'4' => Ok(Provider::ClaudeCode),
        b'7' => Ok(Provider::Pi),
        other => bail!(
            "Unsupported UUID version {} in session ID {:?} (only v4=Claude Code, \
             v7=pi are recognised)",
            other as char,
            session_id
        ),
    }
}

/// Cheap structural check for a hyphenated 36-char UUID.
fn looks_like_hyphenated_uuid(s: &str) -> bool {
    if s.len() != 36 {
        return false;
    }
    let bytes = s.as_bytes();
    bytes[8] == b'-' && bytes[13] == b'-' && bytes[18] == b'-' && bytes[23] == b'-'
}

/// Provider-agnostic session metadata.
///
/// Unified representation of a session from any provider. All fields
/// common to Claude Code and OpenCode are present; provider-specific
/// extras (like `parent_id` for OpenCode sub-agents) use `Option`.
#[derive(Debug, Clone, Serialize)]
pub struct Session {
    pub session_id: String,
    pub provider: Provider,
    pub started_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub project_dir: String,
    pub title: String,
    /// Parent session ID (present for sub-agent sessions in OpenCode).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
}

/// Token usage for a single message exchange.
///
/// All fields represent token counts. Fields not applicable to a given
/// provider default to zero (e.g., `reasoning` is zero for Claude Code,
/// `cache_creation` is zero for OpenCode).
#[derive(Debug, Clone, Default, Serialize)]
pub struct TokenUsage {
    /// Input tokens (prompt tokens sent to the model).
    pub input: u64,
    /// Output tokens (completion tokens generated by the model).
    pub output: u64,
    /// Tokens read from cache.
    pub cache_read: u64,
    /// Tokens written to cache (OpenCode `cache.write`).
    pub cache_write: u64,
    /// Cache creation input tokens (Claude Code `cache_creation_input_tokens`).
    pub cache_creation: u64,
    /// Reasoning/thinking tokens (OpenCode-specific).
    pub reasoning: u64,
}

impl TokenUsage {
    /// Total tokens across all categories.
    pub fn total(&self) -> u64 {
        self.input
            + self.output
            + self.cache_read
            + self.cache_write
            + self.cache_creation
            + self.reasoning
    }

    /// Whether all fields are zero (no token data).
    pub fn is_empty(&self) -> bool {
        self.total() == 0
    }
}

impl Add for TokenUsage {
    type Output = Self;

    fn add(self, rhs: Self) -> Self {
        TokenUsage {
            input: self.input + rhs.input,
            output: self.output + rhs.output,
            cache_read: self.cache_read + rhs.cache_read,
            cache_write: self.cache_write + rhs.cache_write,
            cache_creation: self.cache_creation + rhs.cache_creation,
            reasoning: self.reasoning + rhs.reasoning,
        }
    }
}

impl std::iter::Sum for TokenUsage {
    fn sum<I: Iterator<Item = Self>>(iter: I) -> Self {
        iter.fold(TokenUsage::default(), |acc, x| acc + x)
    }
}

/// Provider-agnostic message with optional token usage.
///
/// Represents a single message exchange (user turn or assistant response)
/// along with its token consumption data when available.
#[derive(Debug, Clone, Serialize)]
pub struct Message {
    /// Unique message identifier.
    pub message_id: String,
    /// Session this message belongs to.
    pub session_id: String,
    /// Provider that produced this message.
    pub provider: Provider,
    /// Role: "user" or "assistant".
    pub role: String,
    /// Model used for this message (if available).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// LLM provider id as reported by the harness — e.g.
    /// `"anthropic"`, `"openai-codex"`.  Not always present:
    /// Claude Code does not record this and it must be inferred
    /// downstream when needed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<String>,
    /// Harness agent name (OpenCode `agent`, Pi sub-agent label).
    /// Diagnostic only — never appears in Git trailers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    /// Harness mode (OpenCode `mode`).  Diagnostic only.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    /// When this message was created.
    pub timestamp: DateTime<Utc>,
    /// Token usage (None for user messages, Some for assistant responses).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokens: Option<TokenUsage>,
}

/// Normalized model attribution for a session, suitable for both
/// human-facing Git trailers and structured (JSON) consumers.
///
/// Construction rules — see [`SessionProvider::resolve_attribution`]:
///
/// * `model_id` is required.  Missing model metadata is a hard error,
///   never a silent fallback.
/// * `llm_provider` is optional; when it has to be inferred (Claude
///   Code does not record one), `llm_provider_inferred` is `true`.
/// * `access_surface` is the harness/CLI the human used (e.g.
///   `"OpenCode"`, `"Pi"`, `"ClaudeCode"`).  Carried in JSON for
///   debugging only — kernel-style trailers omit it.
/// * `agent`, `mode`, `variant` are diagnostic-only.
#[derive(Debug, Clone, Serialize)]
pub struct ModelAttribution {
    pub harness: Provider,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub llm_provider: Option<String>,
    pub llm_provider_inferred: bool,
    pub model_id: String,
    pub access_surface: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub variant: Option<String>,
}

/// Map an `llm_provider` id (as reported by a harness, or inferred from
/// a model id family) to the kernel-style brand name used as
/// `AGENT_NAME` in the `Assisted-by:` trailer.
///
/// The kernel doc spec is:
///   `Assisted-by: AGENT_NAME:MODEL_VERSION`
/// where `AGENT_NAME` is the AI vendor brand (e.g. `Claude`, `GPT`),
/// **not** the access harness.  See
/// <https://www.kernel.org/doc/html/latest/process/coding-assistants.html>.
///
/// Unknown provider ids return `None` — callers must treat this as
/// "cannot build a kernel-canonical trailer" and either error or
/// degrade explicitly, never silently substitute the raw id.
pub fn brand_for_llm_provider(llm_provider: &str) -> Option<&'static str> {
    match llm_provider {
        "anthropic" => Some("Claude"),
        "openai" | "openai-codex" => Some("GPT"),
        "google" | "gemini" => Some("Gemini"),
        "xai" | "grok" => Some("Grok"),
        "meta" | "llama" => Some("Llama"),
        "mistral" => Some("Mistral"),
        "deepseek" => Some("DeepSeek"),
        _ => None,
    }
}

/// Best-effort inference of the LLM provider id from a model id, used
/// when the harness does not record an explicit provider field
/// (Claude Code is the canonical case).
///
/// Returns `Some(provider_id)` only when the model id maps unambiguously
/// to a known family.  Unknown families return `None` so the caller can
/// fail loudly instead of inventing attribution.
pub fn infer_llm_provider_from_model(model_id: &str) -> Option<&'static str> {
    let lower = model_id.to_ascii_lowercase();
    if lower.starts_with("claude-") {
        return Some("anthropic");
    }
    if lower.starts_with("gpt-") || lower.starts_with("o1-") || lower.starts_with("o3-") {
        return Some("openai");
    }
    if lower.starts_with("gemini-") {
        return Some("google");
    }
    if lower.starts_with("grok-") {
        return Some("xai");
    }
    if lower.starts_with("llama-") || lower.starts_with("llama3") || lower.starts_with("llama4") {
        return Some("meta");
    }
    None
}

impl ModelAttribution {
    /// Render the kernel-canonical `Assisted-by:` trailer for this
    /// attribution, e.g. `Assisted-by: Claude:claude-sonnet-4-5`.
    ///
    /// Returns an error when the LLM provider id is missing entirely,
    /// or when it does not map to a known brand.  Both situations would
    /// otherwise produce a non-canonical trailer; see
    /// [`brand_for_llm_provider`] for the supported set.
    pub fn trailer(&self) -> Result<String> {
        let provider_id = self.llm_provider.as_deref().ok_or_else(|| {
            anyhow::anyhow!(
                "cannot build Assisted-by trailer: no llm_provider available \
                     for model {:?} (harness={})",
                self.model_id,
                self.harness
            )
        })?;
        let brand = brand_for_llm_provider(provider_id).ok_or_else(|| {
            anyhow::anyhow!(
                "cannot build Assisted-by trailer: unknown llm_provider {:?} \
                 (no brand mapping; teach `brand_for_llm_provider` if this is real)",
                provider_id
            )
        })?;
        Ok(format!("Assisted-by: {}:{}", brand, self.model_id))
    }
}

/// Trait that each provider backend implements to supply session data.
///
/// Adding a new provider (e.g., Codex) requires only implementing this
/// trait. All CLI actions and cross-provider logic use `SessionProvider`
/// exclusively.
pub trait SessionProvider {
    /// Which provider this adapter serves.
    fn provider(&self) -> Provider;

    /// List all sessions available from this provider.
    fn list_sessions(&self) -> Result<Vec<Session>>;

    /// Check if a session's messages contain the given text.
    fn session_contains_text(&self, session_id: &str, needle: &str) -> bool;

    /// Check if a session includes a tool_use that wrote/edited the given file.
    fn session_edited_file(&self, session_id: &str, file_path: &str) -> bool;

    /// Check if the last N messages of a session contain the given text.
    fn session_tail_contains_text(&self, session_id: &str, needle: &str, last_n: usize) -> bool;

    /// Parse a full conversation transcript from a session.
    fn parse_transcript(&self, session_id: &str) -> Result<Vec<TranscriptEntry>>;

    /// List messages with token usage data for a session.
    ///
    /// Returns messages in chronological order. Token data is present on
    /// assistant messages; user messages have `tokens: None`.
    fn list_messages(&self, session_id: &str) -> Result<Vec<Message>>;

    /// Resolve attribution metadata for the most recent assistant
    /// activity in this session — i.e. who/what wrote the code.
    ///
    /// Implementations should prefer authoritative provider/model fields
    /// recorded by the harness on assistant messages.  Pi
    /// implementations may consult `model_change` events when an
    /// assistant message lacks the metadata.  Claude Code may infer the
    /// LLM provider from the model id family (and must set
    /// `llm_provider_inferred = true` when it does).
    ///
    /// Missing model metadata MUST return `Err`.  A Git hook needs to
    /// know whether attribution is unknown — silent fallback to a
    /// generic value is worse than no trailer at all.
    fn resolve_attribution(&self, session_id: &str) -> Result<ModelAttribution>;
}

/// Get the provider adapter for a given session ID.
///
/// Returns a boxed `SessionProvider` based on the session ID format.
/// Errors when the format is not recognised (see [`detect_provider`]).
pub fn provider_for_session(session_id: &str) -> Result<Box<dyn SessionProvider>> {
    Ok(provider_for(detect_provider(session_id)?))
}

/// Get all available provider adapters.
pub fn all_providers() -> Vec<Box<dyn SessionProvider>> {
    vec![
        Box::new(crate::claudecode::ClaudeCodeProvider),
        Box::new(crate::opencode::OpenCodeProvider),
        Box::new(crate::pi::PiProvider),
    ]
}

/// Get the provider adapter for a specific provider.
pub fn provider_for(provider: Provider) -> Box<dyn SessionProvider> {
    match provider {
        Provider::ClaudeCode => Box::new(crate::claudecode::ClaudeCodeProvider),
        Provider::OpenCode => Box::new(crate::opencode::OpenCodeProvider),
        Provider::Pi => Box::new(crate::pi::PiProvider),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_detect_provider_opencode() {
        assert_eq!(detect_provider("ses_abc123").unwrap(), Provider::OpenCode);
        assert_eq!(detect_provider("ses_").unwrap(), Provider::OpenCode);
    }

    #[test]
    fn test_detect_provider_claudecode_uuidv4() {
        assert_eq!(
            detect_provider("550e8400-e29b-41d4-a716-446655440000").unwrap(),
            Provider::ClaudeCode
        );
    }

    #[test]
    fn test_detect_provider_pi_uuidv7() {
        // Real UUIDv7 from a pi session
        assert_eq!(
            detect_provider("019dddbf-6e66-7709-9a3b-b5a18736f890").unwrap(),
            Provider::Pi
        );
    }

    #[test]
    fn test_detect_provider_rejects_malformed() {
        // Wrong length, missing hyphens, garbage — all must error.
        assert!(detect_provider("some-uuid").is_err());
        assert!(detect_provider("").is_err());
        assert!(detect_provider("not-a-uuid-at-all-really-not-one-here").is_err());
    }

    #[test]
    fn test_detect_provider_rejects_unknown_uuid_version() {
        // UUIDv1 (version digit `1`) is a recognisable UUID but not a
        // version we map to a provider — must error.
        assert!(detect_provider("550e8400-e29b-11d4-a716-446655440000").is_err());
    }

    #[test]
    fn test_provider_as_str() {
        assert_eq!(Provider::ClaudeCode.as_str(), "claudecode");
        assert_eq!(Provider::OpenCode.as_str(), "opencode");
        assert_eq!(Provider::Pi.as_str(), "pi");
    }

    #[test]
    fn test_provider_display() {
        assert_eq!(format!("{}", Provider::ClaudeCode), "claudecode");
        assert_eq!(format!("{}", Provider::OpenCode), "opencode");
        assert_eq!(format!("{}", Provider::Pi), "pi");
    }

    #[test]
    fn test_token_usage_total() {
        let usage = TokenUsage {
            input: 100,
            output: 50,
            cache_read: 200,
            cache_write: 0,
            cache_creation: 300,
            reasoning: 0,
        };
        assert_eq!(usage.total(), 650);
    }

    #[test]
    fn test_token_usage_is_empty() {
        assert!(TokenUsage::default().is_empty());
        assert!(!TokenUsage {
            input: 1,
            ..Default::default()
        }
        .is_empty());
    }

    #[test]
    fn test_token_usage_add() {
        let a = TokenUsage {
            input: 10,
            output: 20,
            cache_read: 30,
            cache_write: 40,
            cache_creation: 50,
            reasoning: 60,
        };
        let b = TokenUsage {
            input: 1,
            output: 2,
            cache_read: 3,
            cache_write: 4,
            cache_creation: 5,
            reasoning: 6,
        };
        let sum = a + b;
        assert_eq!(sum.input, 11);
        assert_eq!(sum.output, 22);
        assert_eq!(sum.cache_read, 33);
        assert_eq!(sum.cache_write, 44);
        assert_eq!(sum.cache_creation, 55);
        assert_eq!(sum.reasoning, 66);
    }

    #[test]
    fn test_brand_for_llm_provider_known() {
        assert_eq!(brand_for_llm_provider("anthropic"), Some("Claude"));
        assert_eq!(brand_for_llm_provider("openai"), Some("GPT"));
        assert_eq!(brand_for_llm_provider("openai-codex"), Some("GPT"));
        assert_eq!(brand_for_llm_provider("google"), Some("Gemini"));
        assert_eq!(brand_for_llm_provider("gemini"), Some("Gemini"));
    }

    #[test]
    fn test_brand_for_llm_provider_unknown_returns_none() {
        // The only acceptable answer for an unmapped provider is None,
        // so callers MUST opt in by extending the table.  Silent
        // fallback would generate non-canonical trailers.
        assert_eq!(brand_for_llm_provider("nonsense-provider"), None);
        assert_eq!(brand_for_llm_provider(""), None);
    }

    #[test]
    fn test_infer_llm_provider_from_model() {
        assert_eq!(
            infer_llm_provider_from_model("claude-sonnet-4-5"),
            Some("anthropic")
        );
        assert_eq!(
            infer_llm_provider_from_model("Claude-Opus-4-7"),
            Some("anthropic")
        );
        assert_eq!(infer_llm_provider_from_model("gpt-5.5"), Some("openai"));
        assert_eq!(infer_llm_provider_from_model("o1-preview"), Some("openai"));
        assert_eq!(
            infer_llm_provider_from_model("gemini-2.0-pro"),
            Some("google")
        );
        assert_eq!(infer_llm_provider_from_model("unknown-model"), None);
        assert_eq!(infer_llm_provider_from_model(""), None);
    }

    #[test]
    fn test_model_attribution_trailer_anthropic() {
        let attr = ModelAttribution {
            harness: Provider::OpenCode,
            llm_provider: Some("anthropic".to_string()),
            llm_provider_inferred: false,
            model_id: "claude-sonnet-4-5".to_string(),
            access_surface: "OpenCode".to_string(),
            agent: Some("build".to_string()),
            mode: Some("build".to_string()),
            variant: None,
        };
        assert_eq!(
            attr.trailer().unwrap(),
            "Assisted-by: Claude:claude-sonnet-4-5"
        );
    }

    #[test]
    fn test_model_attribution_trailer_openai_codex() {
        let attr = ModelAttribution {
            harness: Provider::Pi,
            llm_provider: Some("openai-codex".to_string()),
            llm_provider_inferred: false,
            model_id: "gpt-5.5".to_string(),
            access_surface: "Pi".to_string(),
            agent: None,
            mode: None,
            variant: None,
        };
        assert_eq!(attr.trailer().unwrap(), "Assisted-by: GPT:gpt-5.5");
    }

    #[test]
    fn test_model_attribution_trailer_missing_provider_errors() {
        let attr = ModelAttribution {
            harness: Provider::Pi,
            llm_provider: None,
            llm_provider_inferred: false,
            model_id: "gpt-5.5".to_string(),
            access_surface: "Pi".to_string(),
            agent: None,
            mode: None,
            variant: None,
        };
        assert!(attr.trailer().is_err());
    }

    #[test]
    fn test_model_attribution_trailer_unknown_brand_errors() {
        let attr = ModelAttribution {
            harness: Provider::OpenCode,
            llm_provider: Some("nonsense-provider".to_string()),
            llm_provider_inferred: false,
            model_id: "ns-1".to_string(),
            access_surface: "OpenCode".to_string(),
            agent: None,
            mode: None,
            variant: None,
        };
        let err = attr.trailer().unwrap_err().to_string();
        assert!(err.contains("nonsense-provider"));
        assert!(err.contains("brand_for_llm_provider"));
    }

    #[test]
    fn test_model_attribution_json_shape_is_stable() {
        // Hooks may parse this JSON with brittle scripts.  Lock the
        // exact field set so accidental schema drift fails the build.
        let attr = ModelAttribution {
            harness: Provider::OpenCode,
            llm_provider: Some("anthropic".to_string()),
            llm_provider_inferred: false,
            model_id: "claude-sonnet-4-5".to_string(),
            access_surface: "OpenCode".to_string(),
            agent: Some("build".to_string()),
            mode: Some("build".to_string()),
            variant: None,
        };
        let actual = serde_json::to_value(&attr).unwrap();
        let actual_keys: std::collections::BTreeSet<&str> = actual
            .as_object()
            .unwrap()
            .keys()
            .map(|k| k.as_str())
            .collect();
        let expected_keys: std::collections::BTreeSet<&str> = [
            "harness",
            "llm_provider",
            "llm_provider_inferred",
            "model_id",
            "access_surface",
            "agent",
            "mode",
        ]
        .into_iter()
        .collect();
        assert_eq!(
            actual_keys, expected_keys,
            "ModelAttribution JSON shape changed — update doc/admin.org \
             and hook fixtures before changing the schema. Got: {:?}",
            actual
        );
        // NOTE: `Provider` derives serde with `rename_all = "snake_case"`,
        // which produces `open_code` here.  The CLI action layer
        // serialises via `Provider::as_str()` instead (yielding
        // `opencode`), and that's what the user-facing JSON of
        // `ai-audit assisted-by --json` shows.  This test simply pins
        // the in-struct shape so refactors notice the divergence.
        assert_eq!(actual["harness"], "open_code");
        assert_eq!(actual["llm_provider"], "anthropic");
        assert_eq!(actual["llm_provider_inferred"], false);
        assert_eq!(actual["model_id"], "claude-sonnet-4-5");
    }

    #[test]
    fn test_token_usage_sum() {
        let usages = vec![
            TokenUsage {
                input: 10,
                output: 5,
                ..Default::default()
            },
            TokenUsage {
                input: 20,
                output: 10,
                ..Default::default()
            },
            TokenUsage {
                input: 30,
                output: 15,
                ..Default::default()
            },
        ];
        let total: TokenUsage = usages.into_iter().sum();
        assert_eq!(total.input, 60);
        assert_eq!(total.output, 30);
    }
}
