//! Provider-agnostic abstractions for AI assistant sessions.
//!
//! This module defines the shared types and traits that all provider
//! backends (Claude Code, OpenCode, future providers) must implement.
//! Consumer code (CLI actions, session detection, activity tracking)
//! uses these abstractions exclusively, so adding a new provider
//! requires only implementing `SessionProvider` — no other code changes.

use anyhow::{bail, Result};
use chrono::{DateTime, Utc};
use serde::Serialize;
use std::ops::Add;

use crate::transcript::TranscriptEntry;

/// AI assistant provider identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Provider {
    ClaudeCode,
    OpenCode,
    Pi,
}

impl Provider {
    pub fn as_str(&self) -> &'static str {
        match self {
            Provider::ClaudeCode => "claudecode",
            Provider::OpenCode => "opencode",
            Provider::Pi => "pi",
        }
    }
}

impl std::fmt::Display for Provider {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Detect the provider for a session ID based on its format.
///
/// Recognised formats:
/// - `ses_*` prefix → OpenCode
/// - UUIDv4 (version digit `4`) → Claude Code
/// - UUIDv7 (version digit `7`) → Pi
///
/// Anything else (malformed strings, unknown UUID versions) returns an
/// error.  Loud failure here is intentional: unrecognised IDs are almost
/// always user error or a sign that a new provider exists which the
/// codebase has not yet been taught about.
pub fn detect_provider(session_id: &str) -> Result<Provider> {
    if session_id.starts_with("ses_") {
        return Ok(Provider::OpenCode);
    }
    if !looks_like_hyphenated_uuid(session_id) {
        bail!(
            "Unrecognised session ID format: {:?} (expected ses_* for OpenCode, \
             UUIDv4 for Claude Code, or UUIDv7 for pi)",
            session_id
        );
    }
    // Version nibble is the 15th character (index 14) of a hyphenated UUID.
    match session_id.as_bytes()[14] {
        b'4' => Ok(Provider::ClaudeCode),
        b'7' => Ok(Provider::Pi),
        other => bail!(
            "Unsupported UUID version {} in session ID {:?} (only v4=Claude Code, \
             v7=pi are recognised)",
            other as char,
            session_id
        ),
    }
}

/// Cheap structural check for a hyphenated 36-char UUID.
fn looks_like_hyphenated_uuid(s: &str) -> bool {
    if s.len() != 36 {
        return false;
    }
    let bytes = s.as_bytes();
    bytes[8] == b'-' && bytes[13] == b'-' && bytes[18] == b'-' && bytes[23] == b'-'
}

/// Provider-agnostic session metadata.
///
/// Unified representation of a session from any provider. All fields
/// common to Claude Code and OpenCode are present; provider-specific
/// extras (like `parent_id` for OpenCode sub-agents) use `Option`.
#[derive(Debug, Clone, Serialize)]
pub struct Session {
    pub session_id: String,
    pub provider: Provider,
    pub started_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub project_dir: String,
    pub title: String,
    /// Parent session ID (present for sub-agent sessions in OpenCode).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
}

/// Token usage for a single message exchange.
///
/// All fields represent token counts. Fields not applicable to a given
/// provider default to zero (e.g., `reasoning` is zero for Claude Code,
/// `cache_creation` is zero for OpenCode).
#[derive(Debug, Clone, Default, Serialize)]
pub struct TokenUsage {
    /// Input tokens (prompt tokens sent to the model).
    pub input: u64,
    /// Output tokens (completion tokens generated by the model).
    pub output: u64,
    /// Tokens read from cache.
    pub cache_read: u64,
    /// Tokens written to cache (OpenCode `cache.write`).
    pub cache_write: u64,
    /// Cache creation input tokens (Claude Code `cache_creation_input_tokens`).
    pub cache_creation: u64,
    /// Reasoning/thinking tokens (OpenCode-specific).
    pub reasoning: u64,
}

impl TokenUsage {
    /// Total tokens across all categories.
    pub fn total(&self) -> u64 {
        self.input
            + self.output
            + self.cache_read
            + self.cache_write
            + self.cache_creation
            + self.reasoning
    }

    /// Whether all fields are zero (no token data).
    pub fn is_empty(&self) -> bool {
        self.total() == 0
    }
}

impl Add for TokenUsage {
    type Output = Self;

    fn add(self, rhs: Self) -> Self {
        TokenUsage {
            input: self.input + rhs.input,
            output: self.output + rhs.output,
            cache_read: self.cache_read + rhs.cache_read,
            cache_write: self.cache_write + rhs.cache_write,
            cache_creation: self.cache_creation + rhs.cache_creation,
            reasoning: self.reasoning + rhs.reasoning,
        }
    }
}

impl std::iter::Sum for TokenUsage {
    fn sum<I: Iterator<Item = Self>>(iter: I) -> Self {
        iter.fold(TokenUsage::default(), |acc, x| acc + x)
    }
}

/// Provider-agnostic message with optional token usage.
///
/// Represents a single message exchange (user turn or assistant response)
/// along with its token consumption data when available.
#[derive(Debug, Clone, Serialize)]
pub struct Message {
    /// Unique message identifier.
    pub message_id: String,
    /// Session this message belongs to.
    pub session_id: String,
    /// Provider that produced this message.
    pub provider: Provider,
    /// Role: "user" or "assistant".
    pub role: String,
    /// Model used for this message (if available).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// When this message was created.
    pub timestamp: DateTime<Utc>,
    /// Token usage (None for user messages, Some for assistant responses).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokens: Option<TokenUsage>,
}

/// Trait that each provider backend implements to supply session data.
///
/// Adding a new provider (e.g., Codex) requires only implementing this
/// trait. All CLI actions and cross-provider logic use `SessionProvider`
/// exclusively.
pub trait SessionProvider {
    /// Which provider this adapter serves.
    fn provider(&self) -> Provider;

    /// List all sessions available from this provider.
    fn list_sessions(&self) -> Result<Vec<Session>>;

    /// Check if a session's messages contain the given text.
    fn session_contains_text(&self, session_id: &str, needle: &str) -> bool;

    /// Check if a session includes a tool_use that wrote/edited the given file.
    fn session_edited_file(&self, session_id: &str, file_path: &str) -> bool;

    /// Check if the last N messages of a session contain the given text.
    fn session_tail_contains_text(&self, session_id: &str, needle: &str, last_n: usize) -> bool;

    /// Parse a full conversation transcript from a session.
    fn parse_transcript(&self, session_id: &str) -> Result<Vec<TranscriptEntry>>;

    /// List messages with token usage data for a session.
    ///
    /// Returns messages in chronological order. Token data is present on
    /// assistant messages; user messages have `tokens: None`.
    fn list_messages(&self, session_id: &str) -> Result<Vec<Message>>;
}

/// Get the provider adapter for a given session ID.
///
/// Returns a boxed `SessionProvider` based on the session ID format.
/// Errors when the format is not recognised (see [`detect_provider`]).
pub fn provider_for_session(session_id: &str) -> Result<Box<dyn SessionProvider>> {
    Ok(provider_for(detect_provider(session_id)?))
}

/// Get all available provider adapters.
pub fn all_providers() -> Vec<Box<dyn SessionProvider>> {
    vec![
        Box::new(crate::claudecode::ClaudeCodeProvider),
        Box::new(crate::opencode::OpenCodeProvider),
        Box::new(crate::pi::PiProvider),
    ]
}

/// Get the provider adapter for a specific provider.
pub fn provider_for(provider: Provider) -> Box<dyn SessionProvider> {
    match provider {
        Provider::ClaudeCode => Box::new(crate::claudecode::ClaudeCodeProvider),
        Provider::OpenCode => Box::new(crate::opencode::OpenCodeProvider),
        Provider::Pi => Box::new(crate::pi::PiProvider),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_detect_provider_opencode() {
        assert_eq!(detect_provider("ses_abc123").unwrap(), Provider::OpenCode);
        assert_eq!(detect_provider("ses_").unwrap(), Provider::OpenCode);
    }

    #[test]
    fn test_detect_provider_claudecode_uuidv4() {
        assert_eq!(
            detect_provider("550e8400-e29b-41d4-a716-446655440000").unwrap(),
            Provider::ClaudeCode
        );
    }

    #[test]
    fn test_detect_provider_pi_uuidv7() {
        // Real UUIDv7 from a pi session
        assert_eq!(
            detect_provider("019dddbf-6e66-7709-9a3b-b5a18736f890").unwrap(),
            Provider::Pi
        );
    }

    #[test]
    fn test_detect_provider_rejects_malformed() {
        // Wrong length, missing hyphens, garbage — all must error.
        assert!(detect_provider("some-uuid").is_err());
        assert!(detect_provider("").is_err());
        assert!(detect_provider("not-a-uuid-at-all-really-not-one-here").is_err());
    }

    #[test]
    fn test_detect_provider_rejects_unknown_uuid_version() {
        // UUIDv1 (version digit `1`) is a recognisable UUID but not a
        // version we map to a provider — must error.
        assert!(detect_provider("550e8400-e29b-11d4-a716-446655440000").is_err());
    }

    #[test]
    fn test_provider_as_str() {
        assert_eq!(Provider::ClaudeCode.as_str(), "claudecode");
        assert_eq!(Provider::OpenCode.as_str(), "opencode");
        assert_eq!(Provider::Pi.as_str(), "pi");
    }

    #[test]
    fn test_provider_display() {
        assert_eq!(format!("{}", Provider::ClaudeCode), "claudecode");
        assert_eq!(format!("{}", Provider::OpenCode), "opencode");
        assert_eq!(format!("{}", Provider::Pi), "pi");
    }

    #[test]
    fn test_token_usage_total() {
        let usage = TokenUsage {
            input: 100,
            output: 50,
            cache_read: 200,
            cache_write: 0,
            cache_creation: 300,
            reasoning: 0,
        };
        assert_eq!(usage.total(), 650);
    }

    #[test]
    fn test_token_usage_is_empty() {
        assert!(TokenUsage::default().is_empty());
        assert!(!TokenUsage {
            input: 1,
            ..Default::default()
        }
        .is_empty());
    }

    #[test]
    fn test_token_usage_add() {
        let a = TokenUsage {
            input: 10,
            output: 20,
            cache_read: 30,
            cache_write: 40,
            cache_creation: 50,
            reasoning: 60,
        };
        let b = TokenUsage {
            input: 1,
            output: 2,
            cache_read: 3,
            cache_write: 4,
            cache_creation: 5,
            reasoning: 6,
        };
        let sum = a + b;
        assert_eq!(sum.input, 11);
        assert_eq!(sum.output, 22);
        assert_eq!(sum.cache_read, 33);
        assert_eq!(sum.cache_write, 44);
        assert_eq!(sum.cache_creation, 55);
        assert_eq!(sum.reasoning, 66);
    }

    #[test]
    fn test_token_usage_sum() {
        let usages = vec![
            TokenUsage {
                input: 10,
                output: 5,
                ..Default::default()
            },
            TokenUsage {
                input: 20,
                output: 10,
                ..Default::default()
            },
            TokenUsage {
                input: 30,
                output: 15,
                ..Default::default()
            },
        ];
        let total: TokenUsage = usages.into_iter().sum();
        assert_eq!(total.input, 60);
        assert_eq!(total.output, 30);
    }
}
